---
- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify:
    - reload nginx

- name: Ensure vhost path is created.
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory

- name: Configure sites
  template:
    src: "vhosts.j2"
    dest: "{{ nginx_vhost_path }}/{{ item.id }}.cfg"
    owner: root
    group: root
    mode: "0644"
  when: item.state is defined and item.state == 'present'
  with_items:
    - "{{ nginx_vhosts }}"
  notify:
    - reload nginx

- name: Disabling sites
  file:
    path: "{{ nginx_vhost_path }}/{{ item.id }}.cfg"
    state: "{{ item.state }}"
  when: item.state is defined and item.state == 'absent'
  with_items:
    - "{{ nginx_vhosts }}"
  notify:
    - reload nginx
